#pragma once

#include <cstddef>
#include <cstdint>
#include <vector>

// randomprime's skippable cutscenes (qol-cutscenes "skippable", MIT, see
// NOTICE): room script (SCLY) patches that let every cinematic be skipped,
// generated by tools/gen_skippable_cutscenes.py, plus a few engine tweaks at
// their call sites (grep PortSkipCutscenes::Active).
namespace PortSkipCutscenes {

// The setting, or forced on in randomizer and Archipelago games.
bool Active();
// True when a randomized game forces it on regardless of the setting.
bool Forced();

// Patches the SCLY section of area `mreaId` into `out`. Returns false (and
// leaves `out` empty) when not Active, when the room has no patch, or when
// the room's script doesn't match the disc (a mod replaced it).
bool PatchArea(uint32_t mreaId, const uint8_t* scly, size_t size, std::vector< uint8_t >& out);

// Applies an op stream to a SCLY section (big-endian, as on the disc).
// Returns the number of ops whose target was missing; `out` holds the result
// either way. Exposed for tests.
int ApplyOps(const uint8_t* scly, size_t size, const uint8_t* ops, size_t opsSize,
             std::vector< uint8_t >& out);

} // namespace PortSkipCutscenes
