#!/usr/bin/env python3
"""Generate platform/port_map_pickups.inc: where each item pickup sits, for the map's pickup dots.

Reads the pickup and memory relay of every location in platform/port_ap_locations.inc,
looks the pickup up in its room's script (SCLY) on the disc, and records its
position. It also checks that the pickup activates that memory relay when
collected, since the port reads the relay's mailbox entry to hide the dot::

    python3 tools/gen_map_pickups.py <disc.iso> > platform/port_map_pickups.inc
"""

import os
import re
import struct
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gen_skippable_cutscenes import load_sclys, parse_scly  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PICKUP = 0x11
MEMORY_RELAY = 0x13
ARRIVED = 1
ACTIVATE = 1
MASK = 0x3FFFFFF

LOCATION = re.compile(r"\{(\d+), 0x([0-9A-F]+)u, 0x([0-9A-F]+)u, 0x([0-9A-F]+)u, "
                      r"0x([0-9A-F]+)u, 0x([0-9A-F]+)u, \"([^\"]+)\"\}")


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    locations = []
    with open(os.path.join(ROOT, "platform", "port_ap_locations.inc"), encoding="utf-8") as f:
        for line in f:
            m = LOCATION.match(line)
            if m:
                locations.append((int(m[2], 16), int(m[3], 16), int(m[4], 16), int(m[6], 16), m[7]))
    sclys = load_sclys(sys.argv[1])
    print("// Generated by tools/gen_map_pickups.py from the disc and port_ap_locations.inc.")
    print("// Do not edit.")
    print("// { world MLVL, area MREA, memory relay, position }")
    for world, area, pickup, relay, name in locations:
        _, layers = parse_scly(sclys[area])
        objects = {o["id"] & MASK: o for _, objs in layers for o in objs}
        obj = objects[pickup]
        assert obj["type"] == PICKUP, name
        relays = [t & MASK for state, msg, t in obj["conns"]
                  if state == ARRIVED and msg == ACTIVATE and
                  objects.get(t & MASK, {}).get("type") == MEMORY_RELAY]
        assert relay in relays, (name, hex(relay), [hex(r) for r in relays])
        props = obj["props"]
        name_end = props.index(b"\0", 4) + 1
        x, y, z = struct.unpack_from(">3f", props, name_end)
        print("{0x%08Xu, 0x%08Xu, 0x%08Xu, {%.4ff, %.4ff, %.4ff}}, // %s"
              % (world, area, relay, x, y, z, name))


if __name__ == "__main__":
    main()
