#!/usr/bin/env python3
"""Writes platform/port_ap_world_data.inc: the rooms and elevators an
Archipelago seed's layout options name, with the ids the game knows them by.

Sources (randomprime, MIT, see NOTICE):
  src/pickup_meta.rs.in  ROOM_INFO: every room's name and MREA, per pak
  src/elevators.rs       the elevators: world, room and WorldTransporter id

    python3 tools/gen_ap_world.py <randomprime checkout> [output]

The MetroidAPrime apworld names an elevator by its room ("Transport to Chozo
Ruins West"), and puts the area in front of the four names two areas share
("Chozo Ruins: Transport to Tallon Overworld South").
"""
import os
import re
import sys

# Pak -> (the apworld's area name, MLVL), in the order the apworld searches its
# areas for a starting room's name.
PAKS = [
    ("metroid4.pak", "Tallon Overworld", 0x39F2DE28),
    ("metroid2.pak", "Chozo Ruins", 0x83F6FF6F),
    ("metroid6.pak", "Magmoor Caverns", 0x3EF8237C),
    ("metroid3.pak", "Phendrana Drifts", 0xA8BE6291),
    ("metroid5.pak", "Phazon Mines", 0xB1AC4D65),
    ("metroid7.pak", "Impact Crater", 0xC13B09D1),
    ("metroid1.pak", "Frigate Orpheon", 0x158EFE17),
]


def rooms(path):
    text = open(path).read()
    out = {}
    paks = list(re.finditer(r'\("([Mm]etroid\d\.pak)", &\[', text))
    for i, pak in enumerate(paks):
        end = paks[i + 1].start() if i + 1 < len(paks) else len(text)
        body = text[pak.end():end]
        out[pak.group(1).lower()] = [
            (m.group(2), int(m.group(1), 16))
            for m in re.finditer(
                r'room_id: ResId::<res_id::MREA>::new\(0x([0-9A-Fa-f]+)\),\s*name: "([^"]*)"', body)
        ]
    return out


def elevators(path):
    text = open(path).read()
    text = text[text.index("decl_elevators! {"):text.index("macro_rules! decl_spawn_rooms")]
    out = []
    for m in re.finditer(
            r'pak_name: "([^"]+)",\s*name: "[^"]*",(?:[ \t]*// "([^"\n]+)"?[^\n]*)?\s*mlvl: 0x([0-9a-fA-F]+),'
            r'\s*mrea: 0x([0-9a-fA-F]+),\s*mrea_idx: \d+,\s*scly_id: 0x([0-9a-fA-F]+)', text):
        if m.group(2) is None:
            continue  # the Crater's and the frigate's: not in any mapping
        out.append((m.group(1).lower(), m.group(2), int(m.group(3), 16), int(m.group(4), 16),
                    int(m.group(5), 16)))
    return out


def main():
    src = sys.argv[1]
    here = os.path.dirname(os.path.abspath(__file__))
    dest = sys.argv[2] if len(sys.argv) > 2 else os.path.join(
        here, "..", "platform", "port_ap_world_data.inc")
    by_pak = rooms(os.path.join(src, "src", "pickup_meta.rs.in"))
    area_of = {pak: area for pak, area, _ in PAKS}
    lines = ["// Generated by tools/gen_ap_world.py from randomprime's room and elevator",
             "// tables (MIT, see NOTICE). Do not edit.", "",
             "const char* const kAreas[] = {"]
    for _, area, _ in PAKS:
        lines.append('    "%s",' % area)
    lines += ["};", "", "// Area index, MLVL, MREA, name.", "const Room kRooms[] = {"]
    count = 0
    for index, (pak, area, mlvl) in enumerate(PAKS):
        for name, mrea in by_pak[pak]:
            lines.append('    {%d, 0x%08X, 0x%08X, "%s"},' % (index, mlvl, mrea, name))
            count += 1
    lines += ["};", "", "// The apworld's name, area index, MLVL, MREA, WorldTransporter id.",
              "const Elevator kElevators[] = {"]
    found = elevators(os.path.join(src, "src", "elevators.rs"))
    names = [name for _, name, _, _, _ in found]
    for pak, name, mlvl, mrea, scly in found:
        if names.count(name) > 1:
            name = "%s: %s" % (area_of[pak], name)
        lines.append('    {"%s", %d, 0x%08X, 0x%08X, 0x%08X},' % (
            name, [p for p, _, _ in PAKS].index(pak), mlvl, mrea, scly))
    lines.append("};")
    with open(dest, "w") as out:
        out.write("\n".join(lines) + "\n")
    print("%d rooms, %d elevators -> %s" % (count, len(found), os.path.normpath(dest)))


if __name__ == "__main__":
    main()
