#!/usr/bin/env python3
"""Rasterise packaging/varia-bolt.svg into the icon every platform ships.

The SVG is the only source; everything this writes is committed, so a build
needs neither librsvg nor Pillow. Run it again after changing the artwork:

    /usr/bin/python3 tools/gen_icons.py

Writes:
  packaging/metroid_prime_port.png   256 px, the AppImage's icon
  packaging/metroid_prime_port.ico   16..256 px, linked into the Windows exe
  android/.../drawable-xxxhdpi/ic_launcher_foreground.png   adaptive icon layer
  platform/port_window_icon.inc      64 px RGBA, the window icon set at run time

Needs PyGObject with GdkPixbuf's SVG loader (librsvg) and Pillow.
"""
import pathlib

import gi

gi.require_version("GdkPixbuf", "2.0")
from gi.repository import GdkPixbuf  # noqa: E402
from PIL import Image  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parent.parent
SVG = ROOT / "packaging" / "varia-bolt.svg"
RES = ROOT / "android" / "app" / "src" / "main" / "res"

# An adaptive icon's layers are 108 dp of which launchers show at most the
# middle 72 and guarantee only a 66 dp circle; the artwork is fitted to that.
ADAPTIVE_CANVAS = 432  # 108 dp at xxxhdpi
ADAPTIVE_ART = 264  # 66 dp at xxxhdpi

WINDOW_ICON = 64


def render(size, art=None):
    """The icon on a transparent size x size canvas, the artwork art px wide."""
    art = art or size
    # The SVG loader draws the vector at the size asked for, not a scaled bitmap.
    pixbuf = GdkPixbuf.Pixbuf.new_from_file_at_size(str(SVG), art, art)
    drawn = Image.frombuffer(
        "RGBA", (pixbuf.get_width(), pixbuf.get_height()), pixbuf.get_pixels(), "raw", "RGBA", pixbuf.get_rowstride(), 1
    )
    image = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    image.paste(drawn, ((size - drawn.width) // 2, (size - drawn.height) // 2))
    return image


def write_window_icon(path):
    data = render(WINDOW_ICON).tobytes()
    lines = [
        "// Generated by tools/gen_icons.py from packaging/varia-bolt.svg; do not edit.",
        f"// {WINDOW_ICON}x{WINDOW_ICON} RGBA8, row-major.",
    ]
    for i in range(0, len(data), 16):
        lines.append(",".join(str(b) for b in data[i : i + 16]) + ",")
    path.write_text("\n".join(lines) + "\n")


def main():
    render(256).save(ROOT / "packaging" / "metroid_prime_port.png", optimize=True)

    # Each size is drawn from the vector rather than scaled down from 256.
    sizes = [16, 24, 32, 48, 64, 128, 256]
    frames = [render(s) for s in sizes]
    frames[-1].save(
        ROOT / "packaging" / "metroid_prime_port.ico",
        format="ICO",
        sizes=[(s, s) for s in sizes],
        append_images=frames[:-1],
    )

    foreground = RES / "drawable-xxxhdpi" / "ic_launcher_foreground.png"
    foreground.parent.mkdir(parents=True, exist_ok=True)
    render(ADAPTIVE_CANVAS, ADAPTIVE_ART).save(foreground, optimize=True)

    write_window_icon(ROOT / "platform" / "port_window_icon.inc")


if __name__ == "__main__":
    main()
